### ISSUE TITLE
Make .composition read-only, change setter to method

### ISSUE THREAD

**Issue by tomalec** [Juicy/juicy-composition#3]
Currently `appendChild(documentFragment)` behavior make it really confusing for development and together with messy Polymer 1.x data-binding 

> appendChild behavior:
> ```js
> let newComposition= document.createDocumentFragment();
> // ...
> element.composition = newComposition; // .appendChild(newComposition)
> element.composition == newComposition // false
> ```

**Comment by warpech** [comment]
Closing as no longer relevant
