### ISSUE TITLE
Add default slot if there is none

### ISSUE THREAD

**Issue by tomalec** [Juicy/juicy-composition#4]
### Steps to reproduce
1. Add inline text to the `juicy-composition`
  ```html
<juicy-composition auto-stamp>
  Something
  <span>else</span>
</juicy-composition>
  ```
2. As any composition, so the element will create missing slots
  ```js
element.composition = document.createDocumentFragment();
  ```

#### Live Demo
https://jsbin.com/hazede/3/edit?html,console,output

### Expected result
All nodes should be distributed
```
  Something else
```

### Actual result
Only `ElementNodes` are distributed
```
else
```

### Browsers affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11

### Screenshot

---

While stamping, we should make sure default slot (`<content>`/`<slot>`) is also appended.

**Comment by tomalec** [comment]
The plan is that 
 - `stracounter-include` will add `<slot></slot>` only if there is no composition at all.
 - for merged HTML with `declarative-shadow-dom` HTML Merger will add it on the server-side as yet another `declarative-shadow-dom` entry
 - for specific compositions (ones from DB) designer will have to make it manually (he will get it from defaults as above) 
 - app devs  should be discouraged to create one in their `declarative-shadow-dom`

**Comment by warpech** [comment]
Closing as solved in `starcounter-include`.
